FORMAT: 1A
HOST: api.snapito.com

# Snapito API
Snapito API Image Generation

# Snapit API Root [/]

Introduction text here

## Image, Quick Format [/{type}/{key}/{url}]
### Get Image [GET]
+ Response 200 
+ Parameters
    + type (required, string) ... web, desktop or mobile
    + key (required, string) ... Key
    + url (required, url) ... URL to snapshot (no parameters, path or prefix, just domain name)
    
## Image, Specific Format [/{?url,type,key,delay,freshness}]
### Get Image [GET]
+ Response 302 
+ Parameters
    + type (required, string, `png`) ... web, desktop or mobile
    + key (required, string) ... Key
    + delay (required, integer,`60`) ... Delay in seconds before taking snapshot
    + freshness (required, integer,`86400`) ... Maximum age in seconds the image can be, allows caching.
    + url (required, url) ... URL to snapshot (no parameters, path or prefix, just domain name)

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
